config/routes.rb
<<<<<<< HEAD
FirstApp::Application.routes.draw do
=======
Hello::Application.routes.draw do  
resources :users
resources :microposts
resources :macroposts

>>>>>>> 2400ea81aafe048426fa21323e25ab69ed5cb9da

end

app/models/nousarmicropost.rb
class Nousarmicropost < ActiveRecord::Base
  attr_accessible :content, :user_id
end

app/controllers/nousarmicroposts_controller.rb
class NousarmicropostsController < ApplicationController
  # GET /Nousarmicroposts
  # GET /Nousarmicroposts.json
  def index
    @nousarmicroposts = Nousarmicropost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @nousarmicroposts }
    end
  end

  # GET /Nousarmicroposts/1
  # GET /Nousarmicroposts/1.json
  def show
    @nousarmicropost = Nousarmicropost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @nousarmicropost }
    end
  end

  # GET /Nousarmicroposts/new
  # GET /Nousarmicroposts/new.json
  def new
    @nousarmicropost = Nousarmicropost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @nousarmicropost }
    end
  end

  # GET /Nousarmicroposts/1/edit
  def edit
    @nousarmicropost = Nousarmicropost.find(params[:id])
  end

  # POST /Nousarmicroposts
  # POST /Nousarmicroposts.json
  def create
    @nousarmicropost = Nousarmicropost.new(params[:nousarmicropost])

    respond_to do |format|
      if @nousarmicropost.save
        format.html { redirect_to @nousarmicropost, notice: 'Nousarmicropost was successfully created.' }
        format.json { render json: @nousarmicropost, status: :created, location: @nousarmicropost }
      else
        format.html { render action: "new" }
        format.json { render json: @nousarmicropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /Nousarmicroposts/1
  # PUT /Nousarmicroposts/1.json
  def update
    @nousarmicropost = Nousarmicropost.find(params[:id])

    respond_to do |format|
      if @nousarmicropost.update_attributes(params[:nousarmicropost])
        format.html { redirect_to @nousarmicropost, notice: 'Nousarmicropost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @nousarmicropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /Nousarmicroposts/1
  # DELETE /Nousarmicroposts/1.json
  def destroy
    @nousarmicropost = Nousarmicropost.find(params[:id])
    @nousarmicropost.destroy

    respond_to do |format|
      format.html { redirect_to microposts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/nousarmicroposts_helper.rb
module NousarmicropostsHelper
end

app/views/Nousarmicroposts/_form.html.erb
<%= form_for(@nousarmicropost) do |f| %>
  <% if @nousarmicropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nousarmicropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @nousarmicropost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/Nousarmicroposts/edit.html.erb
<h1>Editing micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @nousarmicropost %> |
<%= link_to 'Back', microposts_path %>

app/views/Nousarmicroposts/index.html.erb
<h1>Listing microposts</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @nousarmicroposts.each do |micropost| %>
  <tr>
    <td><%= micropost.content %></td>
    <td><%= micropost.user_id %></td>
    <td><%= link_to 'Show', micropost %></td>
    <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
    <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Nousarmicropost', new_micropost_path %>

app/views/Nousarmicroposts/new.html.erb
<h1>New micropost</h1>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

app/views/Nousarmicroposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @nousarmicropost.content %>
</p>

<p>
  <b>User:</b>
  <%= @nousarmicropost.user_id %>
</p>


<%= link_to 'Edit', edit_micropost_path(@nousarmicropost) %> |
<%= link_to 'Back', microposts_path %>