config/routes.rb
<<<<<<< HEAD
FirstApp::Application.routes.draw do
=======
Hello::Application.routes.draw do  
resources :users
resources :microposts
resources :macroposts

>>>>>>> 2400ea81aafe048426fa21323e25ab69ed5cb9da

end

app/models/macropost.rb
class Macropost < ActiveRecord::Base
  attr_accessible :content, :user_id
  validates :content, :length => { :manimum => 140 }
end

app/controllers/macroposts_controller.rb
class MacropostsController < ApplicationController
  # GET /macroposts
  # GET /macroposts.json
  def index
    @macroposts = Macropost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @macroposts }
    end
  end

  # GET /macroposts/1
  # GET /macroposts/1.json
  def show
    @macropost = Macropost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @macropost }
    end
  end

  # GET /macroposts/new
  # GET /macroposts/new.json
  def new
    @macropost = Macropost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @macropost }
    end
  end

  # GET /macroposts/1/edit
  def edit
    @macropost = Macropost.find(params[:id])
  end

  # POST /macroposts
  # POST /macroposts.json
  def create
    @macropost = Macropost.new(params[:macropost])

    respond_to do |format|
      if @macropost.save
        format.html { redirect_to @macropost, notice: 'Macropost was successfully created.' }
        format.json { render json: @macropost, status: :created, location: @macropost }
      else
        format.html { render action: "new" }
        format.json { render json: @macropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /macroposts/1
  # PUT /macroposts/1.json
  def update
    @macropost = Macropost.find(params[:id])

    respond_to do |format|
      if @macropost.update_attributes(params[:macropost])
        format.html { redirect_to @macropost, notice: 'Macropost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @macropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /macroposts/1
  # DELETE /macroposts/1.json
  def destroy
    @macropost = Macropost.find(params[:id])
    @macropost.destroy

    respond_to do |format|
      format.html { redirect_to macroposts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/macroposts_helper.rb
module MacropostsHelper
end

app/views/macroposts/_form.html.erb
<%= form_for(@macropost) do |f| %>
  <% if @macropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@macropost.errors.count, "error") %> prohibited this macropost from being saved:</h2>

      <ul>
      <% @macropost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/macroposts/edit.html.erb
<h1>Editing macropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @macropost %> |
<%= link_to 'Back', macroposts_path %>

app/views/macroposts/index.html.erb
<h1>Listing macroposts</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @macroposts.each do |macropost| %>
  <tr>
    <td><%= macropost.content %></td>
    <td><%= macropost.user_id %></td>
    <td><%= link_to 'Show', macropost %></td>
    <td><%= link_to 'Edit', edit_macropost_path(macropost) %></td>
    <td><%= link_to 'Destroy', macropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Macropost', new_macropost_path %>

app/views/macroposts/new.html.erb
<h1>New macropost</h1>

<%= render 'form' %>

<%= link_to 'Back', macroposts_path %>

app/views/macroposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @macropost.content %>
</p>

<p>
  <b>User:</b>
  <%= @macropost.user_id %>
</p>


<%= link_to 'Edit', edit_macropost_path(@macropost) %> |
<%= link_to 'Back', macroposts_path %>